name: MyPy

on:
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@main
        with:
          checkName: 'mypy'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
